# Version: 0.0.1
FROM mcr.microsoft.com/windows/nanoserver:1903
FROM mcr.microsoft.com/dotnet/core/runtime:3.1
MAINTAINER Penner Zhang "pennerz@outlook.com"
COPY  netcoreapp3.0/ /Users/ContainerUser/PineRTable/
EXPOSE 88

